export const ADARKDEEP = {
  scores: {
    str: "ADARKDEEP.scores.str.long",
    int: "ADARKDEEP.scores.int.long",
    dex: "ADARKDEEP.scores.dex.long",
    wis: "ADARKDEEP.scores.wis.long",
    con: "ADARKDEEP.scores.con.long",
    cha: "ADARKDEEP.scores.cha.long",
  },
  scores_short: {
	none: "",
    str: "ADARKDEEP.scores.str.short",
    int: "ADARKDEEP.scores.int.short",
    dex: "ADARKDEEP.scores.dex.short",
    wis: "ADARKDEEP.scores.wis.short",
    con: "ADARKDEEP.scores.con.short",
    cha: "ADARKDEEP.scores.cha.short",
  },
  roll_type: {
    result: "=",
    above: "≥",
    below: "≤"
  },
  saves_short: {
    death: "ADARKDEEP.saves.death.short",
    wand: "ADARKDEEP.saves.wand.short",
    paralysis: "ADARKDEEP.saves.paralysis.short",
    breath: "ADARKDEEP.saves.breath.short",
    spell: "ADARKDEEP.saves.spell.short",
  },
  saves_long: {
    death: "ADARKDEEP.saves.death.long",
    wand: "ADARKDEEP.saves.wand.long",
    paralysis: "ADARKDEEP.saves.paralysis.long",
    breath: "ADARKDEEP.saves.breath.long",
    spell: "ADARKDEEP.saves.spell.long",
  },
  armor : {
    unarmored: "ADARKDEEP.armor.unarmored",
    light: "ADARKDEEP.armor.light",
    heavy: "ADARKDEEP.armor.heavy",
    shield: "ADARKDEEP.armor.shield",
  },
  colors: {
    green: "ADARKDEEP.colors.green",
    red: "ADARKDEEP.colors.red",
    yellow: "ADARKDEEP.colors.yellow",
    purple: "ADARKDEEP.colors.purple",
    blue: "ADARKDEEP.colors.blue",
    orange: "ADARKDEEP.colors.orange",
    white: "ADARKDEEP.colors.white"
  },
  languages: [
    "Common",
    "Lawful",
    "Chaotic",
    "Neutral",
    "Bugbear",
    "Doppelgänger",
    "Dragon",
    "Dwarvish",
    "Elvish",
    "Gargoyle",
    "Gnoll",
    "Gnomish",
    "Goblin",
    "Halfling",
    "Harpy",
    "Hobgoblin",
    "Kobold",
    "Lizard Man",
    "Medusa",
    "Minotaur",
    "Ogre",
    "Orcish",
    "Pixie"
  ],
  tags: {
    melee: "ADARKDEEP.items.Melee",
    missile: "ADARKDEEP.items.Missile",
    slow: "ADARKDEEP.items.Slow",
    twohanded: "ADARKDEEP.items.TwoHanded",
    blunt: "ADARKDEEP.items.Blunt",
    brace: "ADARKDEEP.items.Brace",
    splash: "ADARKDEEP.items.Splash",
    reload: "ADARKDEEP.items.Reload",
    charge: "ADARKDEEP.items.Charge",
  },
  tag_images: {
    melee: "systems/adarkdeep/assets/melee.png",
    missile: "systems/adarkdeep/assets/missile.png",
    slow: "systems/adarkdeep/assets/slow.png",
    twohanded: "systems/adarkdeep/assets/twohanded.png",
    blunt: "systems/adarkdeep/assets/blunt.png",
    brace: "systems/adarkdeep/assets/brace.png",
    splash: "systems/adarkdeep/assets/splash.png",
    reload: "systems/adarkdeep/assets/reload.png",
    charge: "systems/adarkdeep/assets/charge.png",
  },
  monster_saves: {
    0: {
      d: 16,
      w: 18,
      p: 17,
      b: 20,
      s: 19
    },
    1: {
      d: 14,
      w: 16,
      p: 15,
      b: 17,
      s: 17
    },
    3: {
      d: 13,
      w: 15,
      p: 14,
      b: 16,
      s: 16
    },
    5: {
      d: 11,
      w: 13,
      p: 12,
      b: 13,
      s: 14
    },
    7: {
      d: 10,
      w: 12,
      p: 11,
      b: 12,
      s: 13
    },
    9: {
      d: 8,
      w: 10,
      p: 9,
      b: 9,
      s: 11
    },
    11: {
      d: 7,
      w: 9,
      p: 8,
      b: 8,
      s: 10
    },
    13: {
      d: 6,
      w: 7,
      p: 6,
      b: 5,
      s: 8
    },
    15: {
      d: 4,
      w: 6,
      p: 5,
      b: 4,
      s: 7
    },
    17: {
      d: 3,
      w: 5,
      p: 4,
      b: 4,
      s: 6
    },
  },
  monster_thac0: {
    0: 20,
    1: 19,
    2: 18,
    3: 17,
    4: 16,
    5: 15,
    6: 14,
    7: 13,
    9: 12,
    10: 11,
    12: 10,
    14: 9,
    16: 8,
    18: 7,
    20: 6,
    22: 5
  },
  attack_cols: {
    A: 1,
	B: 0,
    C: -1,
    D: -2,
    E: -3,
    F: -4,
    G: -5,
    H: -6,
    I: -7,
    J: -8,
    K: -9,
    L: -10,
    M: -11,
    N: -12,
    O: -13,
    P: -14,
    Q: -15,
    R: -16
  }
};